const recipes = [
  { inputs: ["fire", "water"], output: "steam" },
  { inputs: ["fire", "earth"], output: "lava" },
 { inputs: ["air", "tool"], output: "bellows" },
{ inputs: ["fire", "bellows"], output: "heat" },
{ inputs: ["fire", "air"], output: "smoke" },
{ inputs: ["metal", "wood"], output: "tool" },
  { inputs: ["fire", "air"], output: "heat" },
  { inputs: ["chocolate", "milk"], output: "chocolate milk" },
  { inputs: ["chocolate milk", "heat"], output: "hot chocolate" },
  { inputs: ["water", "earth"], output: "mud" },
  { inputs: ["water", "air"], output: "rain" },
  { inputs: ["earth", "air"], output: "dust" },
  { inputs: ["steam", "air"], output: "cloud" },
  { inputs: ["lava", "water"], output: "stone" },
  { inputs: ["lava", "air"], output: "obsidian" },
  { inputs: ["mud", "water"], output: "clay" },
  { inputs: ["clay", "fire"], output: "brick" },
  { inputs: ["rain", "earth"], output: "plant" },
  { inputs: ["plant", "water"], output: "tree" },
  { inputs: ["tree", "fire"], output: "ash" },
  { inputs: ["tree", "axe"], output: "wood" },
  { inputs: ["ash", "water"], output: "fertilizer" },
  { inputs: ["fertilizer", "mud"], output: "grass" },
  { inputs: ["grass", "air"], output: "hay" },
  { inputs: ["wood", "fire"], output: "charcoal" },
  { inputs: ["charcoal", "water"], output: "ink" },
  { inputs: ["ink", "paper"], output: "book" },
  { inputs: ["dust", "water"], output: "sand" },
  { inputs: ["sand", "fire"], output: "glass" },
  { inputs: ["glass", "water"], output: "bottle" },
  { inputs: ["bottle", "air"], output: "balloon" },
  { inputs: ["clay", "water"], output: "pottery" },
  { inputs: ["pottery", "fire"], output: "ceramic" },
  { inputs: ["rain", "plant"], output: "flower" },
  { inputs: ["flower", "air"], output: "fragrance" },
  { inputs: ["tree", "fire"], output: "charcoal" }, 
  { inputs: ["fragrance", "water"], output: "perfume" },
  { inputs: ["rain", "air"], output: "thunderstorm" },
  { inputs: ["thunderstorm", "fire"], output: "lightning" },
  { inputs: ["lightning", "sand"], output: "glass" },
  { inputs: ["glass", "mud"], output: "terrarium" },
  { inputs: ["terrarium", "plant"], output: "garden" },
  { inputs: ["garden", "water"], output: "pond" },
  { inputs: ["pond", "fish"], output: "aquarium" },
  { inputs: ["dust", "fire"], output: "ash" },
  { inputs: ["ash", "earth"], output: "coal" },
  { inputs: ["coal", "fire"], output: "energy" },
  { inputs: ["energy", "air"], output: "windmill" },
  { inputs: ["windmill", "earth"], output: "factory" },
  { inputs: ["factory", "glass"], output: "greenhouse" },
  { inputs: ["greenhouse", "plant"], output: "forest" },
  { inputs: ["forest", "rain"], output: "jungle" },
  { inputs: ["jungle", "water"], output: "swamp" },
  { inputs: ["swamp", "air"], output: "fog" },
  { inputs: ["fog", "fire"], output: "smoke" },
  { inputs: ["smoke", "water"], output: "smog" },
 // Animals
  { inputs: ["grass", "earth"], output: "animal" },
  { inputs: ["animal", "water"], output: "cow" },
  { inputs: ["animal", "air"], output: "bird" },
  { inputs: ["bird", "nest"], output: "egg" },
  { inputs: ["cow", "grass"], output: "milk" },

  // Sweets and Advanced Cooking Ingredients
  { inputs: ["tree", "sun"], output: "cocoa beans" },
  { inputs: ["cocoa beans", "milk"], output: "chocolate" },
  { inputs: ["rain", "flower"], output: "honey" },

  // Cooking Basics
  { inputs: ["water", "flour"], output: "dough" },
  { inputs: ["dough", "heat"], output: "bread" },
  { inputs: ["bread", "sugar"], output: "cake" },
  { inputs: ["milk", "sugar"], output: "cream" },
  { inputs: ["cream", "fruit"], output: "ice cream" },
  { inputs: ["egg", "flour"], output: "pancake" },
  { inputs: ["chocolate", "milk"], output: "hot chocolate" },
  { inputs: ["bread", "cheese"], output: "sandwich" },
  { inputs: ["water", "coffee beans"], output: "coffee" },

  // Dairy and Other Foods
  { inputs: ["milk", "heat"], output: "butter" },
  { inputs: ["butter", "flour"], output: "pastry" },
  { inputs: ["pastry", "fruit"], output: "pie" },
  { inputs: ["bread", "butter"], output: "toast" },
  { inputs: ["toast", "honey"], output: "sweet toast" },
  { inputs: ["cheese", "bread"], output: "grilled cheese" },

  // Final Advanced Cooking Goal
  { inputs: ["cake", "ice cream"], output: "celebration cake" },
];

export default recipes;
